lane :mam_version do
  version = blackberry_mam_version
  major_version = /(\d+)\..*/.match(version)[1]

  UI.user_error!("Using an outdated version of the GD.sdk, please upgrade") if major_version.to_i < 2
  UI.message("Using #{version} of the GD.sdk")
end

lane :mam_plist do
  update_info_plist_for_blackberry_mam(
    plist: File.absolute_path('../example/ExampleApp/Info.plist'),
    good_entitlement_id: 'com.example.app.good',
    good_entitlement_version: '1.1.0.0',
    export_method: 'enterprise'
  )
end

lane :mam_network_check do
  blackberry_mam_network_check
end

lane :test do
  mam_version
  mam_plist
  mam_network_check
end
